<html>
  <title>
    Transaction Query Results
  </title>
  <body>
    <?php /* handles data generated by tx_query_form.html */
      print "Transaction ID: " <?php echo $_GET["txID"]; ?><br>
      print "Transaction Date: " <?php echo $_GET["txDate"]; ?><br>
      print "Payment Method: " <?php echo $_GET["txPayMethod"]; ?><br>
      print "Comments: " <?php echo $_GET["txComments"]; ?><br>
    ?>
  </body>
</html>
